#!/usr/bin/env bash

FILE=/tmp/.tricks.yaml
PORT=8817

## create deployment file
cat <<EOF > ${FILE}
apiVersion: v1
kind: Pod
metadata:
  name: tricks
  labels:
    tricks: "true"
spec:
  restartPolicy: Never
  containers:
  - name: tricks
    image: vitorenesduarte/tricks
    imagePullPolicy: Always
    env:
    - name: PORT
      value: "${PORT}"
EOF

function is_running {
  kubectl get -f ${FILE} 2>&1 | grep Running
}

function get_ip {
  # TODO check if context is minikube
  minikube service tricks --url
}

function start {
  local _running=$(is_running)
  local _ip=$(get_ip)

  if [ -z "${_running}" ]; then
    echo "Starting Tricks..."
    kubectl create -f ${FILE}
    kubectl expose pod tricks --type=NodePort --port=${PORT}

    echo "Configuring Tricks..."
    while [ -z "${_ip}" ]; do
      _ip=$(get_ip)
      sleep 1
    done

    echo "Tricks configured correctly!"

  else
    if [ -z "${_ip}" ]; then
      echo "Tricks is running, but not configured correctly!"
    fi
  fi
}

function experiment {
  local _yaml=$1
  local _json=/tmp/exp.json

  if [ ! -f ${_yaml} ]; then
    echo "File ${_yaml} not found!"
    exit 1
  fi

  python -c 'import sys, yaml, json; json.dump(yaml.load(sys.stdin), sys.stdout, indent=4)' < ${_yaml} > ${_json}
  cat ${_json}
}

case "$1" in
  start)
    start
    ;;
  exp)
    if [ $# -ne 2 ]; then
      echo "Usage: tricks exp FILE"
      exit 1
    fi
    start
    experiment $2
    ;;
  *)
    echo "Usage: tricks {start|exp}"
    exit 1
esac
